name: Build and Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Inject TRUE_WEB secret into config.js
      - name: Create config.js with secret
        run: |
          echo "const SECRET_URL='${{ secrets.TRUE_WEB }}';" > site/config.js

      # Deploy to GitHub Pages
      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
