name: Deploy Fullscreen Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Replace secret in HTML
        run: |
          sed -i "s|%TRUE_WEB%|${{ secrets.TRUE_WEB }}|g" index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # assuming index.html is in root
